### ISSUE TITLE
Add ability to parse date-time patterns from extent.properties  for folder name

### ISSUE THREAD

**Issue by grasshopper7** [grasshopper7/extentreports-cucumber5-adapter#12]
This will make ensure that repeated runs will not overwrite existing reports. This can be done by adding the current timestamp. Support for a recognizable Java DateTimeFormatter for naming report files or folders.
From this comment - http://grasshopper.tech/1697/#comment-1287

**Comment by bwilliams-bah** [comment]
What about preserving the screenshots for each run as well?

**Comment by grasshopper7** [comment]
The code should take care of renaming the screenshot folder beforehand so everything works when an old report is opened.

**Comment by grasshopper7** [comment]
Added in version 1.5.0

**Comment by bwilliams-bah** [comment]
Awesome. Do you have an example of how this new functionality can be used in our extent.properties file?

**Comment by grasshopper7** [comment]
Sample implementation - https://github.com/grasshopper7/cuke5-extent-adapter-report/tree/master/cuke5-extent-adapter-report. Documentation - http://grasshopper.tech/1697/ Check the 'Customized Report Name' section

**Comment by bwilliams-bah** [comment]
This works great! Thank you @grasshopper7
