### ISSUE TITLE
Displaying duplicate tests if we use tags 

### ISSUE THREAD

**Issue by santosh043** [grasshopper7/extentreports-cucumber5-adapter#16]
Only in tags tab the scenarios are displaying duplicate and in tags section on dashboard page in these two tags places the scenarios displaying duplicate.

these are displaying only if i use Tags in TestRunner. If we dont use tags , then tags tab will dont dispay in the report. But even for tags also should work and it scenarios should display only once.

In report displaying duplicates as below.

STATUS TIMESTAMP TESTNAME
18:34:42 PM Login with valid credentials
Login functionality.Login with valid credentials
18:34:42 PM Login with valid credentials
Login functionality.Login with valid credentials
18:35:13 PM Login with invalid credentials
Login functionality.Login with invalid credentials
18:35:13 PM Login with invalid credentials
Login functionality.Login with invalid credentials

Feature: Login functionality
Description: Login functionality Valid and Invalid Credentials
@LoginTests
Scenario Outline: Login with valid credentials
Given user is on home page
When go to login page
And enter username “” and password “”
And click login button
Then moves to login success page
And user logout of the application
Examples:
| username | | password |
| santosh2006043@gmail.com | | Qwer$123 |

Feature file
----------
@FunctionalTests
Feature: Login functionality Valid and Invalid  Credentials

@LoginTests
Scenario Outline: Login with valid credentials
Given user is on home page
When  go to login page
And  enter username "<username>" and password "<password>"
And  click login button  
Then moves to login success page 
And  user logout of the application
Examples: 
|  username                | password | 
| santosh2006043@gmail.com | Qwer$123 | 

@LoginTests
Scenario Outline: Login with invalid credentials
Given user is on home page
When  go to login page
And  enter username "<username>" and password "<password>"
And  click login button  
Then user see login failure message  
Examples: 
|  username                 | password | 
|  santosh2006043@gmail.com | Qwer$123456     |

**Comment by grasshopper7** [comment]
Can u attach the report in the issue?

**Comment by grasshopper7** [comment]
Closing as no response. Do open if still required.
