### ISSUE TITLE
SparkReporter not generating json file

### ISSUE THREAD

**Issue by rahgir** [grasshopper7/extentreports-cucumber5-adapter#7]
Hi @anshooarora ,
I dont see Json getting generated for SparkReporter similar to feature available via extent object initialization in ExtentReport 4.1.5 version. 
Also, how to configure JSONFormatter in extent-config.xml ?

This was very good feature and would really be helpful if you continue for Cucumber Adapter as well.

Thanks!

**Comment by anshooarora** [comment]
@rahgir  Are you trying to render JSON body in the HTML file, or creating a JSON output from JSONFormatter, or both?

If JSON body - I believe there was a bug in v4.1.5 which was resolved in v4.1.7 - so upgrading should fix.

If JSONFormatter - It would require adding it to the Service, @grasshopper7, can this ticket be marked as an enhancement?

**Comment by grasshopper7** [comment]
@anshooarora Will look into adding the JSONFormatter to the adapter code.

**Comment by rahgir** [comment]
> @rahgir Are you trying to render JSON body in the HTML file, or creating a JSON output from JSONFormatter, or both?
> 
> If JSON body - I believe there was a bug in v4.1.5 which was resolved in v4.1.7 - so upgrading should fix.
> 
> If JSONFormatter - It would require adding it to the Service, @grasshopper7, can this ticket be marked as an enhancement?

Hi, Thanks for the response. I was expecting both. Using existing JSON I should be able to generate Extent report and also test execution should generate JSON. I am already using it in 4.1.5 via code but don’t know how to configure via adapter.

**Comment by grasshopper7** [comment]
JSON formatter has been added to adapter in version 1.4.0. Extent version updated to 4.1.7. Artifact should be available in maven central in a day or so. (Pretty slow in replication since a couple of weeks now). Will update sample implementation and documentation when available.

**Comment by rahgir** [comment]
Thanks much 😊. Will it be possible to merge in cucumber adapter 4 as well ?

**Comment by grasshopper7** [comment]
That repository is not maintained by me. The json formatter functionality is planned to be added to cucumber adapter 4 along with the extentreport version update to 5.0.0.

**Comment by anshooarora** [comment]
@rahgir Will do,  there was an [issue found](https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/63) which was just fixed.  Awaiting confirmation from @grasshopper7 and I will prepare Extent and v4 adapter for release.

**Comment by rahgir** [comment]
Thanks both 😊. Keep up the good work 👍
